-- Run this in the Supabase SQL Editor to create tables, profiles, and RLS policies.

-- Profiles table (extends auth.users)
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  display_name text,
  username text UNIQUE,
  phone text,
  location_geohash text,
  location_lat double precision,
  location_lng double precision,
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read any profile" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Listings table
CREATE TABLE public.listings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id uuid REFERENCES auth.users NOT NULL,
  title text NOT NULL,
  description text,
  price integer NOT NULL,
  condition text CHECK (condition IN ('Mint','Excellent','Good','Fair')),
  category text,
  images text[],
  status text DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE','RESERVED','SOLD')),
  location_geohash text,
  location_lat double precision,
  location_lng double precision,
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view available listings" ON public.listings FOR SELECT USING (status = 'AVAILABLE');
CREATE POLICY "Seller can view own listings" ON public.listings FOR SELECT USING (auth.uid() = seller_id);
CREATE POLICY "Seller can insert listings" ON public.listings FOR INSERT WITH CHECK (auth.uid() = seller_id);
CREATE POLICY "Seller can update own listings" ON public.listings FOR UPDATE USING (auth.uid() = seller_id);

-- Chats table
CREATE TABLE public.chats (
  id text PRIMARY KEY,
  item_id bigint REFERENCES listings(id),
  buyer_id uuid REFERENCES auth.users NOT NULL,
  seller_id uuid REFERENCES auth.users NOT NULL,
  last_message text,
  updated_at timestamp with time zone DEFAULT now(),
  escrow_state jsonb DEFAULT '{}'::jsonb
);

ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Participants can read chat" ON public.chats FOR SELECT USING (auth.uid() = buyer_id OR auth.uid() = seller_id);
CREATE POLICY "Participants can insert chat" ON public.chats FOR INSERT WITH CHECK (auth.uid() = buyer_id OR auth.uid() = seller_id);
CREATE POLICY "Participants can update chat" ON public.chats FOR UPDATE USING (auth.uid() = buyer_id OR auth.uid() = seller_id);

-- Messages table
CREATE TABLE public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id text REFERENCES chats(id) ON DELETE CASCADE,
  sender_id uuid REFERENCES auth.users NOT NULL,
  text text NOT NULL,
  type text DEFAULT 'text',
  timestamp timestamp with time zone DEFAULT now()
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Chat participants can read messages" ON public.messages FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM chats WHERE chats.id = messages.chat_id AND (auth.uid() = chats.buyer_id OR auth.uid() = chats.seller_id)
  )
);

CREATE POLICY "Chat participants can insert messages" ON public.messages FOR INSERT WITH CHECK (
  auth.uid() = sender_id AND EXISTS (
    SELECT 1 FROM chats WHERE chats.id = messages.chat_id AND (auth.uid() = chats.buyer_id OR auth.uid() = chats.seller_id)
  )
);

-- Enable realtime for messages (must also enable in Dashboard > Database > Replication)
ALTER PUBLICATION supabase_realtime ADD TABLE messages;

-- Storage bucket: create manually in dashboard named "listings" with public access, or use this:
-- INSERT INTO storage.buckets (id, name, public) VALUES ('listings', 'listings', true);

-- Storage policy (run separately in Storage section or here):
-- CREATE POLICY "Allow authenticated uploads" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'listings' AND (storage.foldername(name))[1] = auth.uid()::text);
-- CREATE POLICY "Allow public read" ON storage.objects FOR SELECT USING (bucket_id = 'listings');
